In [1]:
import os
import pandas as pd
from IPython.display import clear_output
# assign directory
directory = './result4/'

results = pd.DataFrame({'A' : []})

i = 0

# iterate over files in
# that directory
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        i += 1
        df = pd.read_csv(f)
        results = pd.concat([results, df], ignore_index=True)
    clear_output(wait=True)
    print(str(i)+'/1000')
results = results.drop(columns=['A'])
results

1000/1000

,True persona,True name,True surname,Text,Correct,Predicted persona,Predicted surname,Predicted name
0,http://dati.camera.it/ocd/persona.rdf/p305968,ROBERTO,MARTI,"ROBERTO GIACHETTI La seduta comincia alle 14,05.",False,http://dati.camera.it/ocd/persona.rdf/p300480,GIACHETTI,ROBERTO
1,http://dati.camera.it/ocd/persona.rdf/p34960,FERDINANDO,ADORNATO,"FERDINANDO ADORNATO, Segretario, legge il proc...",False,NaN,NaN,NaN
2,http://dati.camera.it/ocd/persona.rdf/p301561,MICHELE,BORDO,"MICHELE BORDO, Relatore. Signor Presidente, on...",False,NaN,NaN,NaN
3,http://dati.camera.it/ocd/persona.rdf/p302882,ELVIRA,SAVINO,"ELVIRA SAVINO. Grazie, Presidente. Il disegno ...",False,NaN,NaN,NaN
4,http://dati.camera.it/ocd/persona.rdf/p305715,SERGIO,BATTELLI,"SERGIO BATTELLI. Grazie Presidente, come è sta...",False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1196997,http://dati.camera.it/ocd/persona.rdf/p3330,MARIO ADRIANO,LAVAGNOLI,VAGNOLI » . « I sottoscritti chiedono di inter...,False,NaN,NaN,NaN
1196998,http://dati.camera.it/ocd/persona.rdf/p750,GUIDO,BERNARDI,"« BERNARDI, ZAMBERLETTI » . L'onorevole minist...",True,http://dati.camera.it/ocd/persona.rdf/p750,BERNARDI,GUIDO
1196999,http://dati.camera.it/ocd/persona.rdf/p5150,MARIANO,RUMOR,"RUMOR, Ministro dell' interno . Signor Preside...",True,http://dati.camera.it/ocd/persona.rdf/p5150,RUMOR,MARIANO
1197000,http://dati.camera.it/ocd/persona.rdf/p720,ENRICO,BERLINGUER,"BERLINGUER ENRICO . Signor Presi dente, -onore...",True,http://dati.camera.it/ocd/persona.rdf/p720,BERLINGUER,ENRICO
1197001,http://dati.camera.it/ocd/persona.rdf/p5910,ANTONINO,TRIPODI,"TRIPODI ANTONINO. Signor ministro , ella, che ...",True,http://dati.camera.it/ocd/persona.rdf/p5910,TRIPODI,ANTONINO

In [2]:
results['Correct'].describe()

count     1197002
unique          2
top         False
freq       630418
Name: Correct, dtype: object

In [13]:
import os
import pandas as pd
filename = './result2/res' + str(0) + '_' + str(72) + '.csv'
df = pd.read_csv(filename)
c = 'Correct '+str(0)
p = 'Predicted persona ' + str(0)
df = df.rename(columns={"Correct": c, "Predicted persona": p})
df

,True persona,True name,True surname,Text,Correct 0,Predicted persona 0,Predicted surname,Predicted name
0,http://dati.camera.it/ocd/persona.rdf/p18700,GIUSEPPE,ERMINI,ERMINI. Non l’ha liquidato bene.,True,http://dati.camera.it/ocd/persona.rdf/p18700,ERMINI,GIUSEPPE
1,http://dati.camera.it/ocd/persona.rdf/p25560,ROBERTO,CESSI,"CESSI. Onorevole Ermini, io ne conosco EIZhl I...",True,http://dati.camera.it/ocd/persona.rdf/p25560,CESSI,ROBERTO
2,http://dati.camera.it/ocd/persona.rdf/p26930,ANTONIO,SEGNI,"SEGN 1, Ministro della pubblicn istwisione. No...",True,http://dati.camera.it/ocd/persona.rdf/p26930,SEGNI,ANTONIO
3,http://dati.camera.it/ocd/persona.rdf/p25560,ROBERTO,CESSI,"CESSI. M.a esisteva. Questa giunta, clunque, a...",True,http://dati.camera.it/ocd/persona.rdf/p25560,CESSI,ROBERTO
4,http://dati.camera.it/ocd/persona.rdf/p10000,MATTEO,RESCIGNO,RESCIGNO. Le aumentiamo ogni anno quelle scuol...,True,http://dati.camera.it/ocd/persona.rdf/p10000,RESCIGNO,MATTEO
...,...,...,...,...,...,...,...,...
1192,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA C .,False,NaN,NaN,NaN
1193,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA D .,False,NaN,NaN,NaN
1194,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA E .,False,NaN,NaN,NaN
1195,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA F .,False,NaN,NaN,NaN
1196,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA G .,False,NaN,NaN,NaN

In [73]:
import os
import pandas as pd
r = [72,94,105,227,285,374,532,784,815,828]
l = []
for j in r:
    results = pd.DataFrame({'A' : []})
    for i in range(5):
        filename = './result2/res' + str(i) + '_' + str(j) + '.csv'
        df = pd.read_csv(filename)
        c = 'Correct '+str(i)
        p = 'Predicted persona ' + str(i)
        df = df.rename(columns={"Correct": c, "Predicted persona": p})
        results = pd.concat([results, df[[c,p]]], axis = 1)
    results = results.drop(columns=['A'])
    results = results.fillna('Not Found')
    x = set([])
    for i in range(5):
        for j in range(5):
            c1 = 'Correct '+str(i)
            c2 = 'Correct '+str(j)
            for t in list(results[results[c1] != results[c2]].index.values):
                x.add(t)
    for i in range(5):
        for j in range(5):
            c1 = 'Predicted persona '+str(i)
            c2 = 'Predicted persona '+str(j)
            for t in list(results[results[c1] != results[c2]].index.values):
                x.add(t)
    l.append(list(x))
l

[[376, 237, 1141, 221],
 [504, 450, 866],
 [262, 743, 1175, 889, 123],
 [774, 296, 620, 465, 885, 249],
 [322, 50, 371, 372, 762],
 [577, 193, 659, 796],
 [8, 1034, 747, 687, 465],
 [],
 [384, 1057, 846, 401, 564, 348, 61],
 [1058, 483, 262, 1102, 82]]

In [65]:
c1 = 'Correct '+str(1)
c2 = 'Correct '+str(3)
results[results[c1] != results[c2]]
list(results[results[c1] != results[c2]].index.values)

[221, 376]

In [77]:
sum = 0
for i in l:
    sum += len(i)
sum/len(l)

4.4

In [76]:
len(results)

1197

In [80]:
filename = './result/res'+ str(72) + '.csv'
pd.read_csv(filename)

,True persona,True name,True surname,Text,Correct,Predicted persona,Predicted surname,Predicted name
0,http://dati.camera.it/ocd/persona.rdf/p18700,GIUSEPPE,ERMINI,ERMINI. Non l’ha liquidato bene.,True,http://dati.camera.it/ocd/persona.rdf/p18700,ERMINI,GIUSEPPE
1,http://dati.camera.it/ocd/persona.rdf/p25560,ROBERTO,CESSI,"CESSI. Onorevole Ermini, io ne conosco EIZhl I...",True,http://dati.camera.it/ocd/persona.rdf/p25560,CESSI,ROBERTO
2,http://dati.camera.it/ocd/persona.rdf/p26930,ANTONIO,SEGNI,"SEGN 1, Ministro della pubblicn istwisione. No...",True,http://dati.camera.it/ocd/persona.rdf/p26930,SEGNI,ANTONIO
3,http://dati.camera.it/ocd/persona.rdf/p25560,ROBERTO,CESSI,"CESSI. M.a esisteva. Questa giunta, clunque, a...",True,http://dati.camera.it/ocd/persona.rdf/p25560,CESSI,ROBERTO
4,http://dati.camera.it/ocd/persona.rdf/p10000,MATTEO,RESCIGNO,RESCIGNO. Le aumentiamo ogni anno quelle scuol...,True,http://dati.camera.it/ocd/persona.rdf/p10000,RESCIGNO,MATTEO
...,...,...,...,...,...,...,...,...
1192,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA C .,False,NaN,NaN,NaN
1193,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA D .,False,NaN,NaN,NaN
1194,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA E .,False,NaN,NaN,NaN
1195,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA F .,False,NaN,NaN,NaN
1196,http://dati.camera.it/ocd/persona.rdf/p20,TULLIO,ABELLI,TABELLA G .,False,NaN,NaN,NaN

In [81]:
r = [72,94,105,227,285,374,532,784,815,828]
l = []
for j in r:
    results = pd.DataFrame({'A' : []})
    for i in range(5):
        filename = './result3/res' + str(i) + '_' + str(j) + '.csv'
        df = pd.read_csv(filename)
        c = 'Correct '+str(i)
        p = 'Predicted persona ' + str(i)
        df = df.rename(columns={"Correct": c, "Predicted persona": p})
        results = pd.concat([results, df[[c,p]]], axis = 1)
    results = results.drop(columns=['A'])
    results = results.fillna('Not Found')
    x = set([])
    for i in range(5):
        for j in range(5):
            c1 = 'Correct '+str(i)
            c2 = 'Correct '+str(j)
            for t in list(results[results[c1] != results[c2]].index.values):
                x.add(t)
    for i in range(5):
        for j in range(5):
            c1 = 'Predicted persona '+str(i)
            c2 = 'Predicted persona '+str(j)
            for t in list(results[results[c1] != results[c2]].index.values):
                x.add(t)
    l.append(list(x))
l

[[612, 517, 237, 724, 1141, 376, 221],
 [725, 866, 317],
 [262, 743, 1175, 889, 123],
 [774, 296, 620, 1041, 465, 885],
 [994, 322, 50, 371, 762, 191],
 [544, 577, 193, 5, 582, 1069, 796],
 [1093, 8, 1034, 747, 465],
 [211],
 [384, 1057, 401, 564, 88, 348, 61],
 [1058, 483, 262, 1102, 82]]

------------------------
------------------------

[[376, 237, 1141, 221],

 [504, 450, 866],
 
 [262, 743, 1175, 889, 123],
 
 [774, 296, 620, 465, 885, 249],
 
 [322, 50, 371, 372, 762],
 
 [577, 193, 659, 796],
 
 [8, 1034, 747, 687, 465],
 
 [],
 
 [384, 1057, 846, 401, 564, 348, 61],
 
 [1058, 483, 262, 1102, 82]]

--------------------------------------------------------------------------

[[612, 517, 237, 724, 1141, 376, 221],

 [725, 866, 317],
 
 [262, 743, 1175, 889, 123],
 
 [774, 296, 620, 1041, 465, 885],
 
 [994, 322, 50, 371, 762, 191],
 
 [544, 577, 193, 5, 582, 1069, 796],
 
 [1093, 8, 1034, 747, 465],
 
 [211],
 
 [384, 1057, 401, 564, 88, 348, 61],
 
 [1058, 483, 262, 1102, 82]]

------------------------------
DELTA

[ ]/[612, 517, 724,]

[504, 450]/[725, 317]

[ ]/[ ]

[249]/[1041]

[372]/[994, 191]

[659]/[544, 5, 582, 1069]

[687]/[1093]

[ ]/[211]

[846]/[88]

[ ]/[ ]

In [94]:
r = [72,94,105,227,285,374,532,784,815,828]
j = 105
re = pd.DataFrame({'A' : []})
for i in range(5):
    filename = './result2/res' + str(i) + '_' + str(j) + '.csv'
    df1 = pd.read_csv(filename)
    c = 'Correct 1'
    p = 'Predicted persona 1'
    df1 = df1.rename(columns={"Correct": c, "Predicted persona": p})
    filename = './result3/res' + str(i) + '_' + str(j) + '.csv'
    df2 = pd.read_csv(filename)
    c = 'Correct 2'
    p = 'Predicted persona 2'
    df2 = df2.rename(columns={"Correct": c, "Predicted persona": p})
    res = pd.concat([df1[["Correct 1","Predicted persona 1"]], df2[["Correct 2","Predicted persona 2"]]], axis = 1)
    res = res.fillna('Not Found')
    re = pd.concat([re,res[res['Predicted persona 1'] != res['Predicted persona 2']]])
re

,A,Correct 1,Predicted persona 1,Correct 2,Predicted persona 2
123,NaN,False,http://dati.camera.it/ocd/persona.rdf/p50474,False,Not Found
154,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p200419
157,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
177,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
179,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300263
212,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
222,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
262,NaN,False,http://dati.camera.it/ocd/persona.rdf/p301059,False,http://dati.camera.it/ocd/persona.rdf/p300218
291,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
315,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
743,NaN,False,Not Found,True,http://dati.camera.it/ocd/persona.rdf/p300368
889,NaN,False,Not Found,True,http://dati.camera.it/ocd/persona.rdf/p6610
1175,NaN,False,Not Found,True,http://dati.camera.it/ocd/persona.rdf/p5400
154,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p200419
157,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
177,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
179,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300263
212,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
222,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
262,NaN,False,Not Found,False,http://dati.camera.it/ocd/persona.rdf/p301059
291,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
315,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
743,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300368,False,Not Found
123,NaN,False,http://dati.camera.it/ocd/persona.rdf/p50474,False,Not Found
154,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p200419
157,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
177,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
179,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300263
212,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
222,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
262,NaN,False,Not Found,False,http://dati.camera.it/ocd/persona.rdf/p300218
291,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
315,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
1175,NaN,False,Not Found,True,http://dati.camera.it/ocd/persona.rdf/p5400
123,NaN,False,Not Found,False,http://dati.camera.it/ocd/persona.rdf/p50474
154,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p200419
157,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
177,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
179,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300263
212,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
222,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
262,NaN,False,Not Found,False,http://dati.camera.it/ocd/persona.rdf/p301059
291,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
315,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
743,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300368,False,Not Found
1175,NaN,True,http://dati.camera.it/ocd/persona.rdf/p5400,False,Not Found
154,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p200419
157,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
177,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
179,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300263
212,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
222,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
262,NaN,False,http://dati.camera.it/ocd/persona.rdf/p301059,False,http://dati.camera.it/ocd/persona.rdf/p300218
291,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p50074
315,NaN,True,http://dati.camera.it/ocd/persona.rdf/p300292,False,http://dati.camera.it/ocd/persona.rdf/p300486
1175,NaN,False,Not Found,True,http://dati.camera.it/ocd/persona.rdf/p5400

In [107]:
r = [72,94,105,227,285,374,532,784,815,828]
j = 828
for i in range(5):
    filename = './result2/res' + str(i) + '_' + str(j) + '.csv'
    df1 = pd.read_csv(filename)
    print(df1['Correct'].describe())
    print('--------------------------')
    filename = './result3/res' + str(i) + '_' + str(j) + '.csv'
    df2 = pd.read_csv(filename)
    print(df2['Correct'].describe())
    print('==========================')

count     1197
unique       2
top       True
freq       942
Name: Correct, dtype: object
--------------------------
count     1197
unique       2
top       True
freq       942
Name: Correct, dtype: object
==========================
count     1197
unique       2
top       True
freq       941
Name: Correct, dtype: object
--------------------------
count     1197
unique       2
top       True
freq       941
Name: Correct, dtype: object
==========================
count     1197
unique       2
top       True
freq       940
Name: Correct, dtype: object
--------------------------
count     1197
unique       2
top       True
freq       942
Name: Correct, dtype: object
==========================
count     1197
unique       2
top       True
freq       941
Name: Correct, dtype: object
--------------------------
count     1197
unique       2
top       True
freq       940
Name: Correct, dtype: object
==========================
count     1197
unique       2
top       True
freq       940
Name: Correct, dtype: object
--------------------------
count     1197
unique       2
top       True
freq       942
Name: Correct, dtype: object
==========================